//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YoutubePlaylistMaker
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PlaylistDBEntities : DbContext
    {
        public PlaylistDBEntities()
            : base("name=PlaylistDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Playlist> Playlists { get; set; }
        public virtual DbSet<PlaylistSong> PlaylistSongs { get; set; }
        public virtual DbSet<PublicPlaylist> PublicPlaylists { get; set; }
        public virtual DbSet<PublicPlaylistSong> PublicPlaylistSongs { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
