//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YoutubePlaylistMaker
{
    using System;
    using System.Collections.Generic;
    
    public partial class PublicPlaylist
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PublicPlaylist()
        {
            this.PublicPlaylistSongs = new HashSet<PublicPlaylistSong>();
        }
    
        public string Playlist_ID { get; set; }
        public string Name { get; set; }
        public System.DateTime Date_Created { get; set; }
        public System.DateTime Date_Last_Used { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PublicPlaylistSong> PublicPlaylistSongs { get; set; }
    }
}
