//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YoutubePlaylistMaker
{
    using System;
    using System.Collections.Generic;
    
    public partial class PublicPlaylistSong
    {
        public string Unique_ID { get; set; }
        public string Playlist_ID { get; set; }
        public string Youtube_ID { get; set; }
        public int Order_In_Playlist { get; set; }
    
        public virtual PublicPlaylist PublicPlaylist { get; set; }
    }
}
